include:
  - file: "/build/java/template-java-maven.yml"
    project: "platform/pipelines-templates"
    ref: "master"

default:
  image: maven:3.8.6-openjdk-18

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  GIT_DEPTH: 0
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

build-jar:
  image: ghcr.io/graalvm/graalvm-ce:ol7-java17-22.3.0
  before_script:
    - yum install wget -y
    - wget https://dlcdn.apache.org/maven/maven-3/3.9.2/binaries/apache-maven-3.9.2-bin.tar.gz --no-check-certificate
    - tar -xvf apache-maven-3.9.2-bin.tar.gz
    - mv apache-maven-3.9.2 /opt/
    - export M2_HOME='/opt/apache-maven-3.9.2'
    - PATH="$M2_HOME/bin:$PATH"
    - export PATH
    - mvn -version
    - export  GRAALVM_HOME=/opt/graalvm-ce-java17-22.3.0/
    - gu install native-image
  script:
    - mvn package -Pnative -DskipTests
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/target

build-tags:
  variables:
    COMMIT_SHA_FILEPATH: /work/commit.sha
    
build-latest:
  variables:
    COMMIT_SHA_FILEPATH: /work/commit.sha
